// Mock data for Formic demo mode.
// Exports window.FORMIC_MOCK_DATA conforming to the Board interface.

(function () {
  const now = new Date('2026-03-09T08:00:00.000Z').toISOString();
  const hourAgo = new Date('2026-03-09T07:00:00.000Z').toISOString();
  const twoHoursAgo = new Date('2026-03-09T06:00:00.000Z').toISOString();

  const GOAL_ID = 'demo-goal-001';
  const CHILD_1_ID = 'demo-child-001'; // done
  const CHILD_2_ID = 'demo-child-002'; // running
  const CHILD_3_ID = 'demo-child-003'; // blocked
  const CHILD_4_ID = 'demo-child-004'; // todo

  const tasks = [
    {
      id: GOAL_ID,
      title: 'Integrate Stripe Payments',
      status: 'done',
      priority: 'high',
      type: 'goal',
      context: 'Add full Stripe payment processing to the application: SDK setup, checkout session endpoint, webhook handler, and customer portal UI.',
      docsPath: '',
      agentLogs: [],
      pid: null,
      workflowStep: 'complete',
      workflowLogs: {},
      progress: 100,
      createdAt: twoHoursAgo,
      queuedAt: twoHoursAgo,
      startedAt: twoHoursAgo,
      completedAt: hourAgo,
      childTaskIds: [CHILD_1_ID, CHILD_2_ID, CHILD_3_ID, CHILD_4_ID],
      dependsOn: [],
      dependsOnResolved: [],
      parentGoalId: null,
      hasManualSubtasks: false,
      retryCount: 0,
      safePointCommit: null,
      fixForTaskId: null,
    },
    {
      id: CHILD_1_ID,
      title: 'Add Stripe SDK and environment configuration',
      status: 'done',
      priority: 'high',
      type: 'standard',
      context: 'Install the Stripe Node.js SDK, add STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET to .env, and configure the Stripe client singleton in src/server/lib/stripe.ts.',
      docsPath: '',
      agentLogs: [
        '> Reading package.json...',
        '> Installing stripe@14.x via npm...',
        '> Creating src/server/lib/stripe.ts...',
        '> Writing Stripe client singleton with env validation...',
        '> Updating .env.example with STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET...',
        '> Running TypeScript type check...',
        '✓ No type errors found.',
        '> Running npm test...',
        '✓ All 12 tests passed.',
        '> Committing changes...',
        '✓ Committed: feat: add Stripe SDK and environment configuration',
      ],
      pid: null,
      workflowStep: 'complete',
      workflowLogs: {},
      progress: 100,
      createdAt: twoHoursAgo,
      queuedAt: twoHoursAgo,
      startedAt: twoHoursAgo,
      completedAt: hourAgo,
      childTaskIds: [],
      parentGoalId: GOAL_ID,
      dependsOn: [],
      dependsOnResolved: [],
      hasManualSubtasks: false,
      retryCount: 0,
      safePointCommit: 'a1b2c3d',
      fixForTaskId: null,
    },
    {
      id: CHILD_2_ID,
      title: 'Implement checkout session endpoint',
      status: 'running',
      priority: 'high',
      type: 'standard',
      context: 'Create POST /api/payments/checkout-session in src/server/routes/payments.ts. Accept { priceId, successUrl, cancelUrl } and return the Stripe checkout session URL.',
      docsPath: '',
      agentLogs: [
        '> Reading PLAN.md...',
        '> Analysing existing route structure in src/server/routes/...',
        '> Reading src/server/routes/board.ts for pattern reference...',
        '> Reading src/server/lib/stripe.ts...',
        '> Planning checkout session handler...',
        '> Creating src/server/routes/payments.ts...',
        '> Writing POST /api/payments/checkout-session handler...',
        '> Adding request body validation with Zod schema...',
        '> Calling stripe.checkout.sessions.create() with line_items...',
        '> Returning { url: session.url } to client...',
        '> Registering payments route in src/server/index.ts...',
        '> Writing unit tests in test/payments.test.ts...',
        '> Running TypeScript type check...',
        '✓ No type errors found.',
        '> Running npm test...',
        '> test/payments.test.ts: POST /api/payments/checkout-session',
        '  ✓ returns 200 with checkout URL (47ms)',
        '  ✓ returns 400 when priceId is missing (12ms)',
        '  ✓ returns 500 on Stripe API error (31ms)',
        '✓ All 15 tests passed.',
        '> Committing changes...',
      ],
      pid: 12345,
      workflowStep: 'execute',
      workflowLogs: {},
      progress: 75,
      createdAt: twoHoursAgo,
      queuedAt: twoHoursAgo,
      startedAt: hourAgo,
      completedAt: null,
      childTaskIds: [],
      parentGoalId: GOAL_ID,
      dependsOn: [CHILD_1_ID],
      dependsOnResolved: [CHILD_1_ID],
      hasManualSubtasks: false,
      retryCount: 0,
      safePointCommit: null,
      fixForTaskId: null,
    },
    {
      id: CHILD_3_ID,
      title: 'Build payment confirmation webhook handler',
      status: 'blocked',
      priority: 'medium',
      type: 'standard',
      context: 'Create POST /api/payments/webhook to handle Stripe checkout.session.completed events. Verify signature with STRIPE_WEBHOOK_SECRET and update order status in the database.',
      docsPath: '',
      agentLogs: [],
      pid: null,
      workflowStep: 'pending',
      workflowLogs: {},
      progress: 0,
      createdAt: twoHoursAgo,
      queuedAt: null,
      startedAt: null,
      completedAt: null,
      childTaskIds: [],
      parentGoalId: GOAL_ID,
      dependsOn: [CHILD_2_ID],
      dependsOnResolved: [CHILD_2_ID],
      hasManualSubtasks: false,
      retryCount: 0,
      safePointCommit: null,
      fixForTaskId: null,
    },
    {
      id: CHILD_4_ID,
      title: 'Add Stripe customer portal UI components',
      status: 'todo',
      priority: 'low',
      type: 'standard',
      context: 'Build React components for the customer billing portal: SubscriptionStatus, BillingHistory, and ManageSubscription button that redirects to the Stripe Customer Portal.',
      docsPath: '',
      agentLogs: [],
      pid: null,
      workflowStep: 'pending',
      workflowLogs: {},
      progress: 0,
      createdAt: twoHoursAgo,
      queuedAt: null,
      startedAt: null,
      completedAt: null,
      childTaskIds: [],
      parentGoalId: GOAL_ID,
      dependsOn: [CHILD_3_ID],
      dependsOnResolved: [],
      hasManualSubtasks: false,
      retryCount: 0,
      safePointCommit: null,
      fixForTaskId: null,
    },
  ];

  const MOCK_LOG_STREAMS = {
    [CHILD_2_ID]: [
      '> Finalising checkout session route...',
      '> Adding idempotency key support...',
      '> Writing integration test for idempotency...',
      '✓ Idempotency test passed (88ms)',
      '> Adding rate-limit middleware to payments route...',
      '> Running full test suite...',
      '✓ All 15 tests passed.',
      '> Staging changes with git add...',
      '✓ Committed: feat: implement checkout session endpoint',
      '✓ Task complete.',
    ],
  };

  window.FORMIC_MOCK_DATA = {
    board: {
      meta: {
        projectName: 'stripe-demo',
        repoPath: '/demo',
        createdAt: now,
      },
      tasks,
      bootstrapRequired: false,
      guidelinesPath: null,
    },
    MOCK_LOG_STREAMS,
    TASK_IDS: { GOAL_ID, CHILD_1_ID, CHILD_2_ID, CHILD_3_ID, CHILD_4_ID },
  };
})();
