#!/usr/bin/env node
// Auto-generated demo build script.
// Reads src/client/demo.html and inlines the two demo JS files, producing
// a fully self-contained dist-demo/index.html suitable for file:// or static hosting.

import { readFile, writeFile, mkdir, copyFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

async function build() {
  const demoHtmlPath = join(root, 'src', 'client', 'demo.html');
  const mockDataPath = join(root, 'src', 'client', 'demo', 'mockData.js');
  const mockApiPath = join(root, 'src', 'client', 'demo', 'mockApi.js');
  const outDir = join(root, 'dist-demo');
  const outFile = join(outDir, 'index.html');

  console.log('[build:demo] Reading source files...');
  const [html, mockData, mockApi] = await Promise.all([
    readFile(demoHtmlPath, 'utf-8'),
    readFile(mockDataPath, 'utf-8'),
    readFile(mockApiPath, 'utf-8'),
  ]);

  // Replace external script src references with inline script blocks
  let output = html
    .replace(
      '<script src="demo/mockData.js"></script>',
      `<script>\n${mockData}\n</script>`
    )
    .replace(
      '<script src="demo/mockApi.js"></script>',
      `<script>\n${mockApi}\n</script>`
    );

  // Add generation header comment after <!DOCTYPE html>
  const header = '<!-- Auto-generated by scripts/build-demo.js — do not edit directly -->\n';
  output = output.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + header);

  // Rewrite absolute root-relative asset paths to relative for GitHub Pages subdirectory hosting
  output = output
    .replaceAll('href="/manifest.json"', 'href="manifest.json"')
    .replaceAll('href="/icon-192.svg"', 'href="icon-192.svg"')
    .replaceAll('href="/icon-512.svg"', 'href="icon-512.svg"')
    .replaceAll('src="/configStore.js"', 'src="configStore.js"');

  await mkdir(outDir, { recursive: true });

  // Copy required asset files into dist-demo/
  const clientDir = join(root, 'src', 'client');
  await Promise.all([
    copyFile(join(clientDir, 'manifest.json'), join(outDir, 'manifest.json')),
    copyFile(join(clientDir, 'icon-192.svg'), join(outDir, 'icon-192.svg')),
    copyFile(join(clientDir, 'icon-512.svg'), join(outDir, 'icon-512.svg')),
    copyFile(join(clientDir, 'configStore.js'), join(outDir, 'configStore.js')),
    writeFile(join(outDir, '.nojekyll'), '', 'utf-8'),
  ]);

  await writeFile(outFile, output, 'utf-8');

  const sizeKb = (Buffer.byteLength(output, 'utf-8') / 1024).toFixed(1);
  console.log(`[build:demo] ✓ Written dist-demo/index.html (${sizeKb} KB)`);
  console.log('[build:demo] ✓ Copied manifest.json, icon-192.svg, icon-512.svg, configStore.js');
  console.log('[build:demo] ✓ Written dist-demo/.nojekyll');
  console.log('[build:demo] Open with: open dist-demo/index.html');
}

build().catch((err) => {
  console.error('[build:demo] Build failed:', err);
  process.exit(1);
});
